-- MySQL Script generated by MySQL Workbench
-- Tue Mar  3 00:34:10 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema takecare
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema takecare
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `takecare` DEFAULT CHARACTER SET utf8 ;
USE `takecare` ;

-- -----------------------------------------------------
-- Table `takecare`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `takecare`.`utilisateur` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `tel` VARCHAR(45) NOT NULL,
  `date_naissance` DATE NOT NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `takecare`.`medecin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `takecare`.`medecin` (
  `idmedecin` INT NOT NULL,
  `specialite` VARCHAR(45) NOT NULL,
  `localisation` VARCHAR(45) NOT NULL,
  `RPPS` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmedecin`),
  UNIQUE INDEX `RPPS_UNIQUE` (`RPPS` ASC) VISIBLE,
  CONSTRAINT `idmedecin`
    FOREIGN KEY (`idmedecin`)
    REFERENCES `takecare`.`utilisateur` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `takecare`.`Patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `takecare`.`Patient` (
  `idPatient` INT NOT NULL,
  `poids` INT NOT NULL,
  `groupe_sanguin` VARCHAR(5) NOT NULL,
  `localisation` VARCHAR(45) NOT NULL,
  `taille` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPatient`),
  CONSTRAINT `idPatient`
    FOREIGN KEY (`idPatient`)
    REFERENCES `takecare`.`utilisateur` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `takecare`.`consultations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `takecare`.`consultations` (
  `medecin_idmedecin` INTEGER NOT NULL,
  `Patient_idPatient` INT NOT NULL,
  PRIMARY KEY (`medecin_idmedecin`, `Patient_idPatient`),
  INDEX `fk_medecin_has_Patient_Patient1_idx` (`Patient_idPatient` ASC) VISIBLE,
  INDEX `fk_medecin_has_Patient_medecin1_idx` (`medecin_idmedecin` ASC) VISIBLE,
  CONSTRAINT `fk_medecin_has_Patient_medecin1`
    FOREIGN KEY (`medecin_idmedecin`)
    REFERENCES `takecare`.`medecin` (`idmedecin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medecin_has_Patient_Patient1`
    FOREIGN KEY (`Patient_idPatient`)
    REFERENCES `takecare`.`Patient` (`idPatient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
