-- MySQL Script generated by MySQL Workbench
-- Tue Mar  3 00:34:10 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema takecare
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema takecare
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `takecare` DEFAULT CHARACTER SET utf8 ;
USE `takecare` ;

-- -----------------------------------------------------
-- Table `takecare`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `takecare`.`utilisateur` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `motdepasse` VARCHAR(300) NOT NULL,
  `statut` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `takecare`.`medecin`
-- -----------------------------------------------------
create table medecin(
idMed int not null auto_increment,
civilite varchar(120) null,
specialite date null,
convention varchar(120) null,
dateNaiss varchar(120) null,
numeroRue varchar(120) null,
numeroRue2 varchar(120) null,
cite varchar(120) null,
region varchar(120) null,
codePostal int null,
pays varchar(120) null,
phone int null,
autre varchar(360) null,
imageUrl varchar(300) null,
userId int not null,
emailPrive varchar(60) null,
primary key(idMed),
foreign key(userId) references utilisateur(userId));




-- -----------------------------------------------------
-- Table `takecare`.`Patient`
-- -----------------------------------------------------
create table patient(
idPat int not null auto_increment,
genre varchar(120) null,
dateNaiss date null,
numeroRue varchar(120) null,
numeroRue2 varchar(120) null,
cite varchar(120) null,
region varchar(120) null,
codePostal int null,
pays varchar(120) null,
phone int null,
poids int null,
taille int null,
groupeSanguin varchar(6) null,
allergies varchar(10) null,
autreAllergie varchar(360) null,
autre varchar(360) null,
imageUrl varchar(300) null,
userId int not null,
primary key(idPat),
foreign key(userId) references utilisateur(userId));
-- -----------------------------------------------------
-- Table `takecare`.`consultations`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `takecare`.`consultation` (
consId int not null auto_increment,
patId int not null,
medId int not null,
room int ,
etat varchar(30),
primary key(consId),
foreign key(patId) references patient(userId),
foreign key(medId) references medecin(userId));
  
  




-- -----------------------------------------------------
-- Table `takecare`.`attente`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `takecare`.`attente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `carteIdt` VARCHAR(300) ,
  `preuveMed` VARCHAR(300) ,
  `emailPrive` VARCHAR(300) ,
  `userId` int  NOT NULL,
  `statut` VARCHAR(45),
  PRIMARY KEY (`id`)
  foreign key('userId') references utilisateur('userId'),
  )
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
